relative_url: adfssdsdgs 
theme: jekyll-theme-minimal
logo: logo.png
title: STScI's Exocoffee
description: Website for the exoplanetary journal club at STScI
when: [Every other Tuesday at 3 PM.]
where: [Rotunda RE220 + Muller N420 + virtually (BlueJeans).]
